name: frwd
# version: git
version: 0.1.0
summary: A minimal port-forwarder
description: |
  frwd is a _tiny_ port-forwarder written in Go.
  It forwards network data received at a specific TCP or UDP port to a remote or local machine.
  In the case of TCP the forwarding is bidirectional.

# base: core18
grade: stable
confinement: strict

#plugs:
#  read-files:
    #interface: personal-files



parts:
  frwd:
    source: .
    plugin: go
    go-importpath: bitbucket.org/vahidi/frwd

apps:
  frwd:
    command: frwd

